# Site settings
title:          VGTHuang
description:    "Minimal Jekyll theme for storytellers"
# baseurl:        "/tale"
url:            "https://vgthuang.github.io"

# Google Analytics
# google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         VGTHuang
  url:          https://vgthuang.github.io
  email:        scdyhhx@zju.edu.cn

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

remote_theme: chesterhow/tale

# Gems
plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale